Wait until the result is collected.
```
🔥 Errored assertions:
describe IO::Event::Selector::EPoll it behaves like process io it can wait for a process which has terminated already test/io/event/selector/process_io.rb:EPoll:58:15
	⚠ NoMethodError: undefined method `success?' for nil
		test/io/event/selector/process_io.rb:38 block (3 levels) in <top (required)>
```